### ISSUE TITLE
could you please upload the data for your scripts, thanks.

### ISSUE THREAD

**Issue by liamxg** [ViralVerity/phylodynamic_analysis_instructions#1]
@ViralVerity

**Comment by ViralVerity** [comment]
This repo is not intended to include examples, just scripts which can be downloaded and used with standard BEAST outputs, which could be generated using some of the XMLs shown here.

**Comment by ViralVerity** [comment]
The input files you need are the XMLs which you can put into BEAST. You need genomic data, downloaded from genbank or gisaid for them. 

If you want to perform analyses such as these, I recommend going through the tutorials on the BEAST website first (https://beast.community/index.html) as these analyses are advanced. They provide example data.
