### ISSUE TITLE
X = 2n+9 or X = 2n+11?

### ISSUE THREAD

**Issue by liamxg** [ViralVerity/phylodynamic_analysis_instructions#3]
@ViralVerity

**Comment by ViralVerity** [comment]
It actually varies a little bit between different analyses, so you just have to double check what your files look like

**Comment by liamxg** [comment]
@ViralVerity thanks.

**Comment by liamxg** [comment]
BTW, using the last tree as the best tree and as the fix topology tree for the next step, not empirical trees? @ViralVerity?
